### ISSUE TITLE
Upgrade to latest nginx

### ISSUE THREAD

**Issue by alexbeletsky** [socialshop/heroku-buildpack-nginx#1]
First of all, thanks a lot for creating this. This buildpack is one from many that actually works. I'm using that with `dokku` and except I've changed the default directory to `public` instead of `html` it's ready from the box.

One thing though, I see that buildpack is still using 1.6.0 and the latest currently is 1.7.10. I can see you fetching it from s3 (probably private one). 

What do you think to upload 1.7.10 there and change the URL.. Another question, why not directly fetch from nginx web site?

**Comment by adriaandotcom** [comment]
Thanks for your suggestion! You can set your default folder via `env`-variables in Heroku.

Heroku needs a compiled version of nginx, that's why I don't use the nginx download website.

I'm working / testing on the new version of nginx

**Comment by alexbeletsky** [comment]
> You can set your default folder via env-variables in Heroku.

Thanks, I got it from docs/sources.. But with `dokku` it was a little easier to me to change it directly in code.

> I'm working / testing on the new version of nginx

Looking forward to it :)

**Comment by adriaandotcom** [comment]
Too old
