### ISSUE TITLE
Question: using trailing slash issue

### ISSUE THREAD

**Issue by alexbeletsky** [socialshop/heroku-buildpack-nginx#2]
Hey @harianus - don't want to bother you, but really need your help here.

I'm using this build pack for simple static application. The structure, is something like this

```
/build
/css
/images
/pricing
   index.html
index.html
```

`index.html` has a reference to `<a href="pricing/"></a>` which opens just fine. But, if I remove trailing slash, for some reason I got port redirect and page could not be opened (you can just try it [here](http://socialsearch.likeastore.com/pricing/) by opening link, removing trailing stash and pressing enter).

Maybe it's not related to buildpack, but it's rather `dokku` problem..

I [found](http://stackoverflow.com/a/3912675/386751) it's possible to configure nginx to add trailing slashes to all routes. I've tried to [add](https://github.com/alexbeletsky/heroku-buildpack-nginx/commit/b5da8070b9850b45e6cc54db344e84306cc6f8ae) to my fork, but unfortunately got the same result.

In case you have any clue how to solve it, I'll really appreciate you help.

**Comment by adriaandotcom** [comment]
`port 5000` looks like a _dokku_ / _nginx_ problem. 

Maybe this helps?

> [This](http://serverfault.com/questions/174297/nginx-apache-trailing-slash-redirect) should fix problem. Add `proxy_redirect` directive right after `proxy_pass` directive
> `proxy_redirect http://example.com:8080/ http://example.com/;`

http://serverfault.com/questions/351212/nginx-redirects-to-port-8080-when-accessing-url-without-slash

**Comment by adriaandotcom** [comment]
Hopefully this fixed your problem? https://github.com/mgmco/heroku-buildpack-nginx/pull/3

**Comment by alexbeletsky** [comment]
@harianus tried updated version, works as charm. 

This is really great build pack for static apps, thanks a lot for releasing that guys!

One question on latest change https://github.com/mgmco/heroku-buildpack-nginx/blob/master/config/nginx.conf.erb#L66

Do I undestand right, that it will be used for `push-state` enabled application, where for instance I have a client site route `/some-route` and `index.html` will be loaded and client routing triggered?

Why don't use `index.html` as default value?
